name: TWRP - Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Manifest Branch'
        required: true
        default: 'twrp-12.1'
        type: choice
        options:
        - twrp-12.1
        - twrp-11
      DEVICE_TREE:
        description: 'TWRP Device Tree'
        required: true
        default: 'https://github.com/Mostafameesr/Neom_android_device_xiaomi_sweet-TWRP'
      DEVICE_TREE_BRANCH:
        description: 'TWRP Device Tree Branch'
        required: true
        default: 'twrp_12.1'
      DEVICE_PATH:
        description: 'Specify your Device Path'
        required: true
        default: 'device/xiaomi/sweet'
      DEVICE_NAME:
        description: 'Specify your Device Codename'
        required: true
        default: 'sweet'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
              
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: Build Environment
      run: |
        sudo apt update
        sudo apt install aria2 git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig -y
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      
    - name: Set-up Manifest
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/Workspace
        cd ${GITHUB_WORKSPACE}/Workspace
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b ${{ inputs.MANIFEST_BRANCH }}
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        
    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/Workspace
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Building TWRP
      run: |
        cd ${GITHUB_WORKSPACE}/Workspace
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make clean && mka ${{ inputs.BUILD_TARGET }}image

    - name: Set Release Properties
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/Workspace

        DEVICE_TREE_URL="${{ inputs.DEVICE_TREE }}"
        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Workspace/out/target/product/${{ inputs.DEVICE_NAME }}/recovery.img
          Workspace/out/target/product/${{ inputs.DEVICE_NAME }}/*.zip
        name: TWRP Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: TWRP-${{ github.run_id }}
        body: |
          ## TWRP Recovery Build - Unofficial
          Build: ${{ inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ env.DEVICE_TREE_URL }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ env.DEVICE_TREE_URL }}/commit/${{ env.COMMIT_ID }}) during building.
